export const ROUTE_PATHS = {
  home: "/",
  catalog: "/products",
  productDetail: "/products/:slug",
  cart: "/cart",
  checkout: "/checkout",
  checkoutSuccess: "/checkout/success",
  checkoutCancel: "/checkout/cancel",
  orderStatus: "/order/:id",
  accountLogin: "/account/login",
  accountRegister: "/account/register",
  accountOrders: "/account/orders",
  accountForgotPassword: "/account/forgot-password",
  accountResetPassword: "/account/reset-password",
  adminLogin: "/admin/login",
  adminDashboard: "/admin",
  adminProducts: "/admin/products",
  adminCategories: "/admin/categories",
  adminOrders: "/admin/orders",
  adminStoreConfig: "/admin/store-config",
  adminUsers: "/admin/users",
  adminCoupons: "/admin/coupons",
};
